version: '3.6'
x-cache-from:
  - &app-cache-from
    cache_from:
      - ${NGINX_IMAGE:-iw/nginx}
      - ${PHP_IMAGE:-iw/php}

services:

  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pwd
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'

  php:
    image: ${PHP_IMAGE:-iw/php}
    build:
      context: ""
      target: app_php
      <<: *app-cache-from
    volumes:
      - ./:/srv/app:rw
      - ./docker/php/conf.d/api-platform.dev.ini/:/usr/local/etc/php/conf.d/api-platform.ini
      - app-front:/srv/app/public/build
      - app-sf-cache:/srv/app/var

  nginx:
    image: ${NGINX_IMAGE:-iw/nginx}
    build:
      context: ""
      target: app_nginx
      <<: *app-cache-from
    depends_on:
      - php
    volumes:
      - ./public:/srv/app/public:ro
      - app-front:/srv/app/public/build:ro
    ports:
      - "8082:80"

volumes:
  db-data: { }
  app-sf-cache: { }
  app-front: { }